version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mysql321!

      MYSQL_DATABASE: newsdb
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  spring:
    container_name: spring
    image: daybrk/test
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  dbdata: